version: '3.7'

services:
  app:
    build:
      context: .
      dockerfile: docker/fastapi.Dockerfile
    environment:
      - BACKEND_URL=http://host.docker.internal:8000/api/v1
    ports:
      - "3000:8000"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    restart: unless-stopped
