services:
  front:
    build:
      context: .
      dockerfile: docker/fastapi.Dockerfile
      target: dev
    env_file:
      - .env
    ports:
      - "3014:3000"
    restart: unless-stopped
    volumes:
      - "./app:/opt/app/app"
      - "./static:/opt/app/app/static"
      - "./templates:/opt/app/app/templates"
    networks:
      - secrets_net
networks:
  secrets_net:
    name: secrets_net
    external: true
