services:
  fastapi:
    build:
      context: .
      dockerfile: docker/fastapi.Dockerfile
      target: dev
    env_file:
      - .env
    ports:
      - "3001:8000"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    restart: unless-stopped
    volumes:
      - "./app:/opt/app/app"
      - "./static:/opt/app/app/static"
      - "./templates:/opt/app/app/templates"
