version: '3.7'

services:
  app:
    build:
      context: .
      dockerfile: docker/fastapi.Dockerfile
    env_file:
      - .env
    ports:
      - "3000:8000"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    restart: unless-stopped
